### ISSUE TITLE
Task version override not reflected upon packaging

### ISSUE THREAD

**Issue by tsteenbakkers** [microsoft/azure-devops-extension-tasks#147]
Not sure if this is a question / help needed and that i simply don't have the right config or if this is an actual bug.

some background info: we're trying to package multiple build / release tasks into one extension and publish them to our private Azure Devops instance. within the task to package the extension i have selected the option to override task version with only the increment on patch to be changed. We still want to be in control of major / minor version but don't want to be bothered with patching each task with every push towards AzDo.

What i notice is that when i for example add a input to the task.json of one of the tasks in the extension and have the extension packaged as a vsix for later distribution that when i open the vsix artifact the patch number of the changed task (or any other for that matter) do not change.

when publishing the vsix the actual changes are not effectuated as such. If i manually update the patch number in the task.json and have it packaged by your tasks the changes are being reflected on the published environment.

now i'm wondering if there is something which i am doing wrong or need to take in consideration when constructing the task.json so the version can be overridden by your task or maybe i'm missing something else.

i do realize that my question is not complete but i'm typing this from my personal machine which at this moment does not have access to the yaml file used for packaging. when i have access i will update this question.

thanks in advance!

**Comment by jessehouwing** [comment]
When you select the override task version, it uses the Extension Version as a baseline.

So you need to specify the Extension Version property on the package task and then make sure the Patch number is an ever increasing number.

**Comment by tsteenbakkers** [comment]
Thanks for the quick reply. May i suggest that the helpmarkdown be updated with this key information? i understand that it needs some base to increment with but that it uses the manifest version as a base would be handy to know.

however we do set the extension version in the build task but i'm guessing that it is trying to increment with the major part of the extension version right?

so this:

```
- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageAzureDevOpsExtension@2
  displayName: 'Package Extension: '
  inputs:
    patternManifest: |
     vss-extension.json
     vss-extension-tasks.json
    outputPath: '$(Build.ArtifactStagingDirectory)\outputfilename-v0.1.$(build.buildid).vsix'
    extensionVersion: '0.1.$(build.buildid)'
    updateTasksVersion: true
    updateTasksVersionType: patch
    extensionVisibility: private
    extensionPricing: free
```

will probably try to increment with 0 ;) which is why it is not working in our case :) Would it be feasible to change this to something which accepts variables (such as build.buildid) to be more resilient?
