### ISSUE TITLE
Documentation: automate task/extension version

### ISSUE THREAD

**Issue by clark42** [microsoft/azure-devops-extension-tasks#159]
Hello,

I'm a beginner in creating custom Azure Devops extension.

I would like to automate the version update in the pipeline.

I've found your task "Query Extension Version", that contains the "Increase version" option, and the "Output Variable (deprecated)" option.
How does it works? If it's deprecated, what is the best way to achieve this?

Thanks you in advance,

**Comment by jessehouwing** [comment]
`Output variables` are now a standard feature of Pipeline tasks, so we no longer have to supply a field for it.

![image](https://user-images.githubusercontent.com/4173387/73940340-93a80d00-48eb-11ea-92c9-a68f6aa83817.png)

**Comment by yannick-Lapierre** [comment]
Hello, I am developing a YAML build/release process and I see 2 issues:

1. Not on your side, but with the YAML editor, the Output Variable list doesn't exist (it's hard to know which variables are available):
![image](https://user-images.githubusercontent.com/37714992/75049510-9baaa400-54ca-11ea-80ad-42cbe44973cb.png)

1. The default output variable doesn't work:

```
          $x = "$(Extension.Version)"
          Write-Host $x
```
Result:
```
Extension.Version : The term 'Extension.Version' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At D:\a\_temp\2815d271-d188-49fa-ba27-2240731fa557.ps1:2 char:9
+ $x = "$(Extension.Version)"
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Extension.Version:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```
if I Set output varibales:
`outputVariable: 'Extension.PackageVersion'`
```
          $x = "$(Extension.PackageVersion)"
          Write-Host $x
```

```
"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'd:\a\_temp\1ae2e18e-a3bd-4d0b-b9c0-f06c15123a0c.ps1'"
1.0.1
Finishing: PowerShell
```

**Comment by jessehouwing** [comment]
See: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables

**Comment by jessehouwing** [comment]
The format would have to reference the   variable's source task name before the extension version bit.

**Comment by jessehouwing** [comment]
This works:

```
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TfxInstaller@101
  inputs:
    version: 'v0.7.x'

- task: QueryAzureDevOpsExtensionVersion@101
  displayName: 'Query the version on the marketplace'
  name: 'Q'
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'marketplace-developertools'
    publisherId: 'jessehouwing'
    extensionId: 'vsts-ensire-tests-dev'
    versionAction: 'None'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "$(Q.Extension.Version)"
    pwsh: true
```
