### ISSUE TITLE
Query Extension Version - SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Nusserdt** [microsoft/azure-devops-extension-tasks#181]
I have an Issue with the **Query Extension Version** Task:

```
          - task: QueryAzureDevOpsExtensionVersion@3
            inputs:
              connectTo: 'TFS'
              connectedServiceNameTFS: 'Gallery'  # Change to whatever you named the service connection
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              versionAction: 'Patch'
              outputVariable: 'Task.Extension.Version'
```

The pipeline give me the feedback:

> ##[error]SyntaxError: Unexpected end of JSON input

We use a **Azure DevOps Server 2019.1** (on premise). When I use the Marketplace connection:

```
              connectTo: 'VsTeam'
              connectedServiceName: 'Marketplace' # Change to whatever you named the service connection
```

I get a `error: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn\'t expired.',` so unfortunately it is no alternative.

Executing the command locally everything works fine (extension **SampleTask** is currently not part of the gallery, it is a inital push, that why `null` should be a correct response):
```
tfx extension show --json --no-color --service-url https://my-server.de/ --auth-type pat --token *** --publisher TEST --extension-id 4a5dd7a5-af8c-xxx
(node:13168) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
null
```

Full Log of `Unexpected end of JSON input`:

```
##[section]Starten: QueryAzureDevOpsExtensionVersion
==============================================================================
Task         : Query Extension Version
Description  : Queries the current version from the Visual Studio Marketplace
Version      : 3.1.45
Author       : Microsoft Corporation
Help         : 
==============================================================================
[command]C:\windows\system32\cmd.exe /D /S /C "D:\AzureDevOpsData\agents\MyAgent.0\_work\_tool\tfx\0.7.11\x64\tfx.cmd extension show --json --no-color --service-url https://my-server.de/ --auth-type pat --token *** --publisher TEST --extension-id 4a5dd7a5-af8c-xxx"
 0 [ '[command]C:\\windows\\system32\\cmd.exe /D /S /C "D:\\AzureDevOpsData\\agents\\MyAgent.0\\_work\\_tool\\tfx\\0.7.11\\x64\\tfx.cmd extension show --json --no-color --service-url https://my-server.de/ --auth-type pat --token *** --publisher TEST --extension-id 4a5dd7a5-af8c-xxx"\r',
  '' ]
 1 [ '[command]C:\\windows\\system32\\cmd.exe /D /S /C "D:\\AzureDevOpsData\\agents\\MyAgent.0\\_work\\_tool\\tfx\\0.7.11\\x64\\tfx.cmd extension show --json --no-color --service-url https://my-server.de/ --auth-type pat --token *** --publisher TEST --extension-id 4a5dd7a5-af8c-xxx"\r',
  '' ]
(node:8856) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency 0 [ '(node:8856) Warning: Accessing non-existent property \'padLevels\' of module exports inside circular dependency',
  '(Use `node --trace-warnings ...` to show where the warning was created)',
  '' ]
(Use `node --trace-warnings ...` to show where the warning was created) 1 [ '(node:8856) Warning: Accessing non-existent property \'padLevels\' of module exports inside circular dependency',
  '(Use `node --trace-warnings ...` to show where the warning was created)',
  '' ]
 2 [ '(node:8856) Warning: Accessing non-existent property \'padLevels\' of module exports inside circular dependency',
  '(Use `node --trace-warnings ...` to show where the warning was created)',
  '' ]
null 0 [ 'null', '' ]
 1 [ 'null', '' ]

 0 [ '\r', '' ]
 1 [ '\r', '' ]
##[error]SyntaxError: Unexpected end of JSON input
##[section]Abschließen: QueryAzureDevOpsExtensionVersion
```
