### ISSUE TITLE
tfx.cmd failed with exit code 3221225477

### ISSUE THREAD

**Issue by Nusserdt** [microsoft/azure-devops-extension-tasks#182]
Ola I am almost done with [Add a custom pipelines task extension](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task). Only the final push with the task **Publish Extension** to the Gallery of my **Azure DevOps Server 2019.1 (on premise)** fails.

The Error Message is:
> ##[error]tfx failed with error: Error: The process 'D:\AzureDevOpsData\agents\MyAgent\_work\_tool\tfx\0.7.11\x64\tfx.cmd' failed with exit code 3221225477

### My YAML declaration looks like:

```
          - task: PublishAzureDevOpsExtension@3
            inputs:
               connectTo: 'TFS'
               connectedServiceNameTFS: 'Gallery'
               fileType: 'vsix'
               vsixFile: '$(System.DefaultWorkingDirectory)/Extensions/*.vsix'
               publisherId: '$(PublisherID)'
               extensionId: '$(ExtensionID)'
               extensionName: '$(ExtensionName)'
               updateTasksVersion: false
               extensionVisibility: 'private'
```

### Locally on the self hosted agent everything works fine:

```
tfx extension publish --json --no-color --service-url https://my-server.de/ --auth-type pat --token *** --vsix TEST.SampleTask-0.1.1.gen.vsix --debug-log-stream stderr
(node:7340) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
{
    "packaged": null,
    "published": true,
    "shared": null
}
```

### The full log is:

```
##[section]Starten: PublishAzureDevOpsExtension
==============================================================================
Task         : Publish Extension
Description  : Publish an Azure DevOps extension to the Visual Studio Marketplace
Version      : 3.1.45
Author       : Microsoft Corporation
Help         : 
==============================================================================
[command]D:\AzureDevOpsData\agents\MyAgent.0\_work\_tasks\PublishAzureDevOpsExtension_631511b4-50ab-47c8-b766-7ae2aa672733\3.1.45\node_modules\7zip-bin-win\x64\7za.exe x D:\AzureDevOpsData\agents\MyAgent.0\_work\41\s\Extensions\TEST.SampleTask-0.1.2.vsix -oC:\Users\TEST-SV~1\AppData\Local\Temp\vsixeditor1201118-9528-1bigcvl.3y6cmfs9k9 -y -spd -aoa

7-Zip (a) 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28

Scanning the drive for archives:
1 file, 7397 bytes (8 KiB)

Extracting archive: D:\AzureDevOpsData\agents\MyAgent.0\_work\41\s\Extensions\TEST.SampleTask-0.1.2.vsix
--
Path = D:\AzureDevOpsData\agents\MyAgent.0\_work\41\s\Extensions\TEST.SampleTask-0.1.2.vsix
Type = zip
Physical Size = 7397

Everything is Ok

Folders: 3
Files: 13
Size:       12785
Compressed: 7397
[command]D:\AzureDevOpsData\agents\MyAgent.0\_work\_tasks\PublishAzureDevOpsExtension_631511b4-50ab-47c8-b766-7ae2aa672733\3.1.45\node_modules\7zip-bin-win\x64\7za.exe a TEST.SampleTask-0.1.2.gen.vsix C:\Users\TEST-SV~1\AppData\Local\Temp\vsixeditor1201118-9528-1bigcvl.3y6cmfs9k9\* -r -y -tzip -mx9

7-Zip (a) 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28

Scanning the drive:
3 folders, 13 files, 12667 bytes (13 KiB)

Creating archive: TEST.SampleTask-0.1.2.gen.vsix

Add new data to archive: 3 folders, 13 files, 12667 bytes (13 KiB)


Files read from disk: 13
Archive size: 7863 bytes (8 KiB)
Everything is Ok
##[warning]Ignoring Share - Not available on TFS.
[command]C:\windows\system32\cmd.exe /D /S /C "D:\AzureDevOpsData\agents\MyAgent.0\_work\_tool\tfx\0.7.11\x64\tfx.cmd extension publish --json --no-color --service-url https://my-server.de/ --auth-type pat --token *** --vsix TEST.SampleTask-0.1.2.gen.vsix --debug-log-stream stderr"
 0 [ '[command]C:\\windows\\system32\\cmd.exe /D /S /C "D:\\AzureDevOpsData\\agents\\MyAgent.0\\_work\\_tool\\tfx\\0.7.11\\x64\\tfx.cmd extension publish --json --no-color --service-url https://my-server.de/ --auth-type pat --token *** --vsix TEST.SampleTask-0.1.2.gen.vsix --debug-log-stream stderr"\r',
  '' ]
 1 [ '[command]C:\\windows\\system32\\cmd.exe /D /S /C "D:\\AzureDevOpsData\\agents\\MyAgent.0\\_work\\_tool\\tfx\\0.7.11\\x64\\tfx.cmd extension publish --json --no-color --service-url https://my-server.de/ --auth-type pat --token *** --vsix TEST.SampleTask-0.1.2.gen.vsix --debug-log-stream stderr"\r',
  '' ]

 0 [ '\r', '' ]
 1 [ '\r', '' ]
##[error]tfx failed with error: Error: The process 'D:\AzureDevOpsData\agents\MyAgent.0\_work\_tool\tfx\0.7.11\x64\tfx.cmd' failed with exit code 3221225477
```

What does the error code `3221225477` mean?
