### ISSUE TITLE
[FR] QueryAzureDevOpsExtensionVersion should return a default value

### ISSUE THREAD

**Issue by Herve-M** [microsoft/azure-devops-extension-tasks#186]
Hello, 

I would like to propose to add the feature on `QueryAzureDevOpsExtensionVersion` task to be able to return a default value in case of no extension is found on the marketplace. 

This case could happen if your extension has never been deployed, like the first time a CI/CD run. 

Thanks,
Hervé

**Comment by jessehouwing** [comment]
There is an override variable you can specify. That way you can queue it
once with that variable set.

**Comment by Herve-M** [comment]
Yes true but this solution would mean to update the CI/CD as it's not easy to do ternary alike condition, not really great for a CI/CD template 😅

**Comment by jessehouwing** [comment]
The trick is to set:

```
          - task: QueryAzureDevOpsExtensionVersion@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'msdevlabs'
              publisherId: 'msdevlabs'
              extensionId: 'vsts-developer-tools-build-tasks'
              versionAction: 'None'
              extensionVersionOverride: 'UseThisVersion'
```

Then use a Queue time variable to set the version:

![image](https://user-images.githubusercontent.com/4173387/108326981-2d76eb00-71cb-11eb-83d1-a9859bf376c0.png)

When the variable is defined and has a value, it will override whatever the queryversion action would do.

You can also use this to bump to a new major or minor version by setting it once to say `3.0.0`, if your previous version was in the `2.4.x` range, after the publish succeeds, new builds will start to use the `3.0.x` version range.
