### ISSUE TITLE
PublishAzureDevOpsExtension@3 is not updating the version

### ISSUE THREAD

**Issue by artur-carvalho** [microsoft/azure-devops-extension-tasks#203]
I'm creating  a pipeline to publish our extension to Marketplace, everything is working fine except the update version part.

I created a service connection and I'm using it, if I set the updateTasksVersion to false the pipeline works fine, if I set it to true and select any of the 3 options then the pipeline fails saying that the version already exists. If I update the version manually to the next one it works, but when I rerun the pipeline this should automatically update the version and publish, but I receive the same error.

I have a vss-extension.json file, if a run the command locally with --rev-version the version is updated but not using this extension.

I also have a task.json file inside a subfolder but this is also not being updated.

This is my pipeline.

```
stages:
- stage: Publish_Extension
  displayName: "Publish Extension"
  jobs:
    - job: Publish_Extension
      displayName: "Create and Publish extension to Marketplace"
      steps:
        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node'

        - script: |
            npm install
            npm install -g tfx-cli
          displayName: 'Run npm install'

        - task: TfxInstaller@3
          displayName: 'Install TFX Cli'
          inputs:
            version: '0.9.x'
            checkLatest: true

- task: PublishAzureDevOpsExtension@3
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'svc-connection'
    fileType: 'manifest'
    updateTasksVersion: true
    updateTasksVersionType: 'minor'
    updateTasksId: true
```

I also tried to use the package task and output to a file, and the package works, but when the publish run using the file as input I receive this error:

```
##[error]tfx failed with error: Error: Extension Version was not supplied nor does the extension manifest define one.
```

I would like to know if this is a bug or the right way to use it.

Thanks in advance,
