### ISSUE TITLE
##[error]Unable to find Tfx version 'v0.11.x'

### ISSUE THREAD

**Issue by ncook-hxgn** [microsoft/azure-devops-extension-tasks#226]
Running the task to install tfx-cli as instructed [here](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#step-6-create-a-build-and-release-pipeline-to-publish-the-extension-to-marketplace), but with default parameters (and on windows instead of ubuntu), results in the task failing.

```yaml
pool:
  vmImage: windows-latest

steps:
- task: TfxInstaller@3
  inputs:
    version: 'v0.11.x'
```
yields
`##[error]Unable to find Tfx version 'v0.11.x'`

Do I need to create a variable group about my Visual Studio MarketPlace Publisher before I install the tfx-cli? Surely not?
