### ISSUE TITLE
"The user with identifier .... does not exist" on publish

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/azure-devops-extension-tasks#348]
Hi, 

First of all, thanks for your work on this extension - we find it very useful indeed!

We're using this task to publish and we've just started experiencing "The user with identifier .... does not exist" messages on publish.  Sometimes this prevents publishing, sometimes it does not.  It started happening in the last week.

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/1010525/211899632-66604d0a-6d4a-4698-9170-a917258775bc.png">

Task usage looks like this:

```yml
          - task: PublishAzureDevOpsExtension@3
            displayName: Publish Extension
            inputs:
              connectTo: VsTeam
              connectedServiceName: $(vsmServiceConnection)
              fileType: vsix
              vsixFile: "**/*.vsix"
              publisherId: $(publisherID)
              extensionId: $(extensionID)
              extensionName: $(extensionName)
              updateTasksVersion: false
              extensionVisibility: private
              extensionPricing: free
```

First failure Monday 10th January 9:49 GMT

https://dev.azure.com/investec/investec-cloud-experience/_build/results?buildId=382172&view=logs&j=cf68489b-58bf-561d-47d9-2db9edb195e7&t=8b142399-646b-50cb-94b5-faa623fe259b
Is there anything we should be aware of do you know?  

Also raised here: https://developercommunity.visualstudio.com/t/The-user-with-identifier--does-not/10250690
